---
name: Screenkit

on:
  workflow_dispatch:
    inputs:
      episode:
        type: string
        description: "Episode number (e.g. 001)"
        required: true
      tts_preset_name:
        description: "TTS preset name"
        default: ""
        type: choice
        options:
          - say
          - espeak
          - eleven_labs
          - eleven_labs_mp3_192k
      overwrite:
        type: boolean
        description: "Regenerate files"
      match:
        type: string
        description: "Match pattern for segments (e.g. 001)"
        default: ""

jobs:
  screenkit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Screenkit
        uses: fnando/screenkit@2018734daadffbbfe64797889db59b0ab815f8fd
        with:
          episode: ${{ github.event.inputs.episode }}
          tts_preset_name: ${{ github.event.inputs.tts_preset_name }}
          tts_api_key: ${{ secrets.ELEVENLABS_API_KEY }}
          overwrite: ${{ github.event.inputs.overwrite }}
          match: ${{ github.event.inputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
